### ISSUE TITLE
Syntax error in example code.

### ISSUE THREAD

**Issue by aero** [plicease/FFI-TinyCC#2]
Hi,

https://github.com/plicease/FFI-TinyCC/blob/master/example/ffi_platypus.pl
and
https://github.com/plicease/FFI-TinyCC/blob/master/lib/FFI/TinyCC.pm#L30
don't seem to work.

Need  "s/function/attach/" ??

**Comment by plicease** [comment]
Exactly, I wrote that when Platypus was in pre-CPAN and the attach was confusingly called function (hence I changed it before went to CPAN).  Thanks for catching that and bringing it to my attention!

**Comment by plicease** [comment]
Should be fixed in 0.17 on its way to CPAN.
